### ISSUE TITLE
Is there a way to submit a question on stackoverflow with stackr package?

### ISSUE THREAD

**Issue by MarcinKosinski** [dgrtwo/stackr#4]
I've seen `stackr` package in this answer to [SO question](http://meta.stackexchange.com/questions/174972/stackoverflow-api-for-r). There are also links to other R packages that communicate with stackoverflow API. Did you consider using `stackr` to submit a question on stackoverflow from R console?

**Comment by dgrtwo** [comment]
Right now, the stackr package covers only the read functions of the Stack Exchange API. I'm moderately inclined to keep it that way, since I see the main point of the package to be data analysis rather than serving as a front-end to ask or answer questions. I think asking questions directly from the R console is dangerous since it doesn't show the question preview, formatting help, or related questions- asking via the web interface has many advantages that serve as quality control.

This would also involve a non-trivial amount of development, since it involves logging in (which may be through OAuth or other sources), and dealing with every kind of error condition for which a question may be rejected (e.g. if Stack Overflow's quality control filter rejects it, or if a captcha is shown, you need to deal with that).

The [reprex](https://github.com/jennybc/reprex) package is working on some great approaches to make asking Stack Overflow questions about R easier. But at the end the last step is still to open the browser and ask. I think it's a small enough step to be worth it!
